spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5200/jimmer_demo
    username: root
    password: 123456
  redis:
    host: localhost
    port: 5400
  kafka:
    consumer:
      bootstrap-servers: localhost:5100
      group-id: jimmer-demo/sql-kt
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: MANUAL_IMMEDIATE

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
